language: rust
script:
  - cargo test -- --test-threads=1
jobs:
  include:
    - stage: rust-stable
      rust: stable
    - stage: rust-beta
      rust: beta
    - stage: rust-nightly
      rust: nightly
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
addons:
    apt:
        packages:
            - libssl-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo install cargo-tarpaulin
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    # code coverage: codecov.io & coveralls.io
    cargo tarpaulin --run-types Tests Doctests --ignore-tests --out Xml --ciserver travis-ci --coveralls $TRAVIS_JOB_ID -- --test-threads=1
    bash <(curl -s https://codecov.io/bash)
  fi
